
-- This script creates and populates the Company database in Oracle DBMS
-------------------------------------------------------
-- 1. Drop tables

DROP TABLE DEPARTMENT cascade CONSTRAINTS;
DROP TABLE EMPLOYEE cascade CONSTRAINTS;
DROP TABLE DEPENDENT cascade CONSTRAINTS;
DROP TABLE DEPT_LOCATIONS cascade CONSTRAINTS;
DROP TABLE PROJECT cascade CONSTRAINTS;
DROP TABLE WORKS_ON cascade CONSTRAINTS;

-------------------------------------------------------
-- 2. Create tables with PK and FK

CREATE TABLE DEPARTMENT(
DNUMBER NUMBER(2) NOT NULL,
DNAME VARCHAR(50) NOT NULL,
MGRSSN NUMBER(9)NOT NULL,
MGRSTARTDATE DATE NOT NULL,
CONSTRAINT DEPT_DNUM_PK PRIMARY KEY (DNUMBER));


CREATE TABLE EMPLOYEE(
SSN NUMBER (9) NOT NULL,
FNAME VARCHAR(25) NOT NULL,
MINIT VARCHAR(1),
LNAME VARCHAR(25) NOT NULL,
BDATE DATE NOT NULL,
ADDRESS VARCHAR(150) NOT NULL,
SEX VARCHAR(1) NOT NULL,
SALARY FLOAT,
SUPERSSN NUMBER(9),
DNO NUMBER(2) NOT NULL,
CONSTRAINT EMP_SSN_PK PRIMARY KEY(SSN),
CONSTRAINT EMP_DNO_FK FOREIGN KEY (DNO) REFERENCES DEPARTMENT(DNUMBER));


CREATE TABLE DEPENDENT(
ESSN NUMBER(9) NOT NULL,
DEPENDENT_NAME VARCHAR(50) NOT NULL,
SEX VARCHAR(1) NOT NULL,
BDATE DATE NOT NULL,
RELATIONSHIP VARCHAR(15) NOT NULL,
CONSTRAINT DEP_ESSN_NAME_PK PRIMARY KEY(ESSN, DEPENDENT_NAME),
CONSTRAINT DEP_ESSN_FK FOREIGN KEY (ESSN) REFERENCES EMPLOYEE(SSN));


CREATE TABLE DEPT_LOCATIONS(
DNUMBER NUMBER(2) NOT NULL,
DLOCATION VARCHAR(50) NOT NULL,
CONSTRAINT DEPTLOC_DNUM_DLOC_PK PRIMARY KEY(DNUMBER, DLOCATION),
CONSTRAINT DEPTLOC_DNUM_FK FOREIGN KEY (DNUMBER) REFERENCES DEPARTMENT(DNUMBER));


CREATE TABLE PROJECT(
PNUMBER NUMBER(3) NOT NULL,
PNAME VARCHAR(25) NOT NULL,
PLOCATION VARCHAR(50),
DNUM NUMBER(2) NOT NULL,
CONSTRAINT PROJ_PNUM_PK PRIMARY KEY (PNUMBER) ,
CONSTRAINT PROJ_DNUM_FK FOREIGN KEY (DNUM) REFERENCES DEPARTMENT(DNUMBER));


CREATE TABLE WORKS_ON(
ESSN NUMBER(9) NOT NULL,
PNO NUMBER(3) NOT NULL,
DNUM FLOAT,
CONSTRAINT WRK_ESSN_PNO_PK PRIMARY KEY (ESSN, PNO),
CONSTRAINT WRK_ESSN_FK FOREIGN KEY (ESSN) REFERENCES EMPLOYEE(SSN),
CONSTRAINT WRK_PNO_FK FOREIGN KEY (PNO) REFERENCES PROJECT(PNUMBER));


 
-------------------------------------------------------
-- 3. Create indexes
--
-- 3.1. Drop indexes

DROP INDEX DEPTLOC_DNUM_IDX;
DROP INDEX PROJ_DNUM_IDX;
DROP INDEX EMP_DNO_IDX;
DROP INDEX DEP_ESSN_IDX;
DROP INDEX WRK_ESSN_IDX;
DROP INDEX WRK_PNO_IDX;

-- 3.2. Create indexes

CREATE INDEX DEPTLOC_DNUM_IDX ON DEPT_LOCATIONS(DNUMBER);
CREATE INDEX PROJ_DNUM_IDX ON PROJECT(DNUM);
CREATE INDEX EMP_DNO_IDX ON EMPLOYEE(DNO);
CREATE INDEX DEP_ESSN_IDX ON DEPENDENT(ESSN);
CREATE INDEX WRK_ESSN_IDX ON WORKS_ON(ESSN);
CREATE INDEX WRK_PNO_IDX ON WORKS_ON(PNO);


-------------------------------------------------------
-- 4. grant privileges

grant select on DEPARTMENT to public;
grant select on EMPLOYEE to public;
grant select on DEPENDENT to public;
grant select on DEPT_LOCATIONS to public;
grant select on PROJECT to public;
grant select on WORKS_ON to public;


-------------------------------------------------------
-- 5. Insert values to SPJ's tables

----Department Table------

INSERT INTO DEPARTMENT (DNAME,DNUMBER,MGRSSN,MGRSTARTDATE) VALUES ('research',5,333445555,TO_DATE('78-05-22','yy-mm-dd'));
INSERT INTO DEPARTMENT (DNAME,DNUMBER,MGRSSN,MGRSTARTDATE) VALUES ('administration',4,987987987,TO_DATE('85-01-01','yy-mm-dd'));
INSERT INTO DEPARTMENT (DNAME,DNUMBER,MGRSSN,MGRSTARTDATE) VALUES ('headquarters',1,888665555,TO_DATE('71-06-19','yy-mm-dd'));

-----Employee Table------

INSERT INTO EMPLOYEE(FNAME,MINIT,LNAME,SSN,BDATE,ADDRESS,SEX,SALARY,SUPERSSN,DNO) VALUES (	'John',	'B',	'Smith',	123456789,	TO_DATE ('55/01/09','yy/mm/dd'),	'731 Fondren, Houston, TX',	'M',	30000,	333445555,	5	);
INSERT INTO EMPLOYEE(FNAME,MINIT,LNAME,SSN,BDATE,ADDRESS,SEX,SALARY,SUPERSSN,DNO) VALUES (	'Franklin',	'T',	'Wong',	333445555,	TO_DATE ('45/12/08','yy/mm/dd'),	'638 Voss, Houston, TX',	'M',	40000,	888665555,	5	);
INSERT INTO EMPLOYEE(FNAME,MINIT,LNAME,SSN,BDATE,ADDRESS,SEX,SALARY,SUPERSSN,DNO) VALUES (	'Alicia',	'J',	'Zelaya',	999887777,	TO_DATE ('58/07/19','yy/mm/dd'),	'3321 Castle, Spring, TX',	'F',	25000,	987654321,	4	);
INSERT INTO EMPLOYEE(FNAME,MINIT,LNAME,SSN,BDATE,ADDRESS,SEX,SALARY,SUPERSSN,DNO) VALUES (	'Jennifer',	'S',	'Wallace',	987654321,	TO_DATE ('31/06/20','yy/mm/dd'),	'231 Berry, Bellaire, TX',	'F',	43000,	888665555,	4	);
INSERT INTO EMPLOYEE(FNAME,MINIT,LNAME,SSN,BDATE,ADDRESS,SEX,SALARY,SUPERSSN,DNO) VALUES (	'Ramesh',	'K',	'Narayan',	666884444,	TO_DATE ('52/08/15','yy/mm/dd'),	'975 Fire Oak, Humble, TX',	'M',	38000,	333445555,	5	);
INSERT INTO EMPLOYEE(FNAME,MINIT,LNAME,SSN,BDATE,ADDRESS,SEX,SALARY,SUPERSSN,DNO) VALUES (	'Joyce',	'A',	'English',	453453453,	TO_DATE ('62/07/31','yy/mm/dd'),	'5631 Rice, Houston, TX',	'F',	25000,	333445555,	5	);
INSERT INTO EMPLOYEE(FNAME,MINIT,LNAME,SSN,BDATE,ADDRESS,SEX,SALARY,SUPERSSN,DNO) VALUES (	'Ahmad',	'V',	'Jabbar',	987987987,	TO_DATE ('59/03/29','yy/mm/dd'),	'980 Dallas, Houston, TX',	'M',	25000,	987654321,	4	);
INSERT INTO EMPLOYEE(FNAME,MINIT,LNAME,SSN,BDATE,ADDRESS,SEX,SALARY,DNO) VALUES (	'James',	'E',	'Borg',	888665555,	TO_DATE ('27/11/10','yy/mm/dd'),	'450 Stone, Houston, TX',	'M',	55000,		1	);


------Dependent Table--------
INSERT INTO DEPENDENT (ESSN,DEPENDENT_NAME,SEX,BDATE,RELATIONSHIP) VALUES (	333445555,	'Alice',	'F',	TO_DATE ('76/04/05','yy/mm/dd'),	'DAUGHTER'	);
INSERT INTO DEPENDENT (ESSN,DEPENDENT_NAME,SEX,BDATE,RELATIONSHIP) VALUES (	333445555,	'Theodore',	'M',	TO_DATE ('73/10/25','yy/mm/dd'),	'SON'	);
INSERT INTO DEPENDENT (ESSN,DEPENDENT_NAME,SEX,BDATE,RELATIONSHIP) VALUES (	333445555,	'Joy',	'F',	TO_DATE ('48/05/03','yy/mm/dd'),	'SPOUSE'	);
INSERT INTO DEPENDENT (ESSN,DEPENDENT_NAME,SEX,BDATE,RELATIONSHIP) VALUES (	987654321,	'Abner',	'M',	TO_DATE ('32/02/29','yy/mm/dd'),	'SPOUSE'	);
INSERT INTO DEPENDENT (ESSN,DEPENDENT_NAME,SEX,BDATE,RELATIONSHIP) VALUES (	123456789,	'Michael',	'M',	TO_DATE ('78/01/01','yy/mm/dd'),	'SON'	);
INSERT INTO DEPENDENT (ESSN,DEPENDENT_NAME,SEX,BDATE,RELATIONSHIP) VALUES (	123456789,	'Alice',	'F',	TO_DATE ('78/12/31','yy/mm/dd'),	'DAUGHTER'	);
INSERT INTO DEPENDENT (ESSN, DEPENDENT_NAME,SEX,BDATE,RELATIONSHIP) VALUES (123456789,	'Elizabeth',	'F',	TO_DATE ('57/05/05','yy/mm/dd'),	'SPOUSE'	);

-----Department Location Table--------

INSERT INTO DEPT_LOCATIONS(DNUMBER,DLOCATION) VALUES (	1,	'Houston'	);
INSERT INTO DEPT_LOCATIONS(DNUMBER,DLOCATION) VALUES (	4,	'Stafford'	);
INSERT INTO DEPT_LOCATIONS(DNUMBER,DLOCATION) VALUES (	5,	'Bellaire'	);
INSERT INTO DEPT_LOCATIONS(DNUMBER,DLOCATION) VALUES (	5,	'Sugarland'	);
INSERT INTO DEPT_LOCATIONS(DNUMBER,DLOCATION) VALUES (	5,	'Houston'	);


-----Project Table-----------
INSERT INTO PROJECT(PNAME,PLOCATION,DNUM,PNUMBER) VALUES (	'ProductX',	'Bellaire',	5,	1	);
INSERT INTO PROJECT(PNAME,PLOCATION,DNUM,PNUMBER) VALUES (	'ProductY',	'Sugarland',	5,	2	);
INSERT INTO PROJECT(PNAME,PLOCATION,DNUM,PNUMBER) VALUES (	'ProductZ',	'Houston',	5,	3	);
INSERT INTO PROJECT(PNAME,PLOCATION,DNUM,PNUMBER) VALUES (	'Computerization',	'Stafford',	4,	10	);
INSERT INTO PROJECT(PNAME,PLOCATION,DNUM,PNUMBER) VALUES (	'Reorganization',	'Houston',	1,	20	);
INSERT INTO PROJECT(PNAME,PLOCATION,DNUM,PNUMBER) VALUES (	'Newbenefits',	'Stafford',	4,	30	);


-----------Work On Table-------------
INSERT INTO WORKS_ON (ESSN,PNO,DNUM) VALUES (	123456789,	1,	32.5	);
INSERT INTO WORKS_ON (ESSN,PNO,DNUM) VALUES (	123456789,	2,	7.5	);
INSERT INTO WORKS_ON (ESSN,PNO,DNUM) VALUES (	666884444,	3,	40	);
INSERT INTO WORKS_ON (ESSN,PNO,DNUM) VALUES (	453453453,	1,	20	);
INSERT INTO WORKS_ON (ESSN,PNO,DNUM) VALUES (	453453453,	2,	20	);
INSERT INTO WORKS_ON (ESSN,PNO,DNUM) VALUES (	333445555,	2,	10	);
INSERT INTO WORKS_ON (ESSN,PNO,DNUM) VALUES (	333445555,	3,	10	);
INSERT INTO WORKS_ON (ESSN,PNO,DNUM) VALUES (	333445555,	10,	10	);
INSERT INTO WORKS_ON (ESSN,PNO,DNUM) VALUES (	333445555,	20,	10	);
INSERT INTO WORKS_ON (ESSN,PNO,DNUM) VALUES (	999887777,	30,	30	);
INSERT INTO WORKS_ON (ESSN,PNO,DNUM) VALUES (	999887777,	10,	10	);
INSERT INTO WORKS_ON (ESSN,PNO,DNUM) VALUES (	987987987,	10,	35	);
INSERT INTO WORKS_ON (ESSN,PNO,DNUM) VALUES (	987987987,	30,	5	);
INSERT INTO WORKS_ON (ESSN,PNO,DNUM) VALUES (	987654321,	30,	20	);
INSERT INTO WORKS_ON (ESSN,PNO,DNUM) VALUES (	987654321,	20,	15	);
INSERT INTO WORKS_ON (ESSN,PNO) VALUES (	888665555,	20		);















